backend:
  name: github
  repo: JohnnyDreamguns/johnny-dreamguns

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: News
    folder: content/news
    create: true
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "select",
          options: ["news", "song"],
        }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: songs
    label: Songs
    folder: content/songs
    create: true
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "select",
          options: ["news", "song"],
        }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
